export * from './GenreBedge/GenreBedge'
export * from './Headers/Headers'
export * from './MoviasListCard/MovieListCard'
export * from './MovieInfo/MovieInfo'
export * from './MoviesList/MoviesList'
export * from './PosterPreview/PosterPreview'
export * from './StarsRating/StarRating'
export * from './UserInfo/UserInfo'